package main

// Empirical test: replicates the binding of Watcharr's WatchedAddRequest
// (encoding/json + play-ground/validator) against the exact JSON bodies
// the extension sends when importing.

import (
	"encoding/json"
	"fmt"
	"time"
)

// Exactly like in Watcharr (server/domain/watched.go), but without validator
// tags here (we check those manually below so no go-mod dependency is needed).
type WatchedAddRequest struct {
	ContentType string    `json:"contentType"`
	TMDBID      int       `json:"tmdbId"`
	Status      string    `json:"status"`
	WatchedDate time.Time `json:"watchedDate,omitempty"`
}

var validContentTypes = map[string]bool{"movie": true, "tv": true, "game": true}

func main() {
	// Exact bodies as generated by the extension (history import):
	bodies := []struct {
		name string
		body string
	}{
		{"Movie with watchedDate (toISOString, RFC3339+ms)",
			`{"contentType":"movie","tmdbId":12345,"status":"FINISHED","watchedDate":"2024-01-15T22:10:00.000Z"}`},
		{"Series with watchedDate (toISOString, RFC3339+ms)",
			`{"contentType":"tv","tmdbId":67890,"status":"WATCHING","watchedDate":"2024-01-15T22:10:00.000Z"}`},
		{"Movie without watchedDate",
			`{"contentType":"movie","tmdbId":12345,"status":"FINISHED"}`},
		{"Series without watchedDate",
			`{"contentType":"tv","tmdbId":67890,"status":"WATCHING"}`},
		// Negative cases for comparison:
		{"tmdbId as string (must FAIL)",
			`{"contentType":"tv","tmdbId":"67890","status":"WATCHING"}`},
		{"watchedDate with comma instead of dot (may fail)",
			`{"contentType":"movie","tmdbId":1,"status":"FINISHED","watchedDate":"2024-01-15T22:10:00,000Z"}`},
		{"watchedDate in local format without offset",
			`{"contentType":"movie","tmdbId":1,"status":"FINISHED","watchedDate":"2024-01-15 22:10:00"}`},
	}

	for _, b := range bodies {
		var ar WatchedAddRequest
		err := json.Unmarshal([]byte(b.body), &ar)

		// Binding wie Gin: unmarshal + Validierung (oneof + max)
		bindErr := err
		if err == nil {
			if !validContentTypes[ar.ContentType] {
				bindErr = fmt.Errorf("key: 'WatchedAddRequest.ContentType' Error:Field validation for 'ContentType' failed on the 'oneof' tag")
			}
		}

		status := "OK (200)"
		if bindErr != nil {
			status = "FAIL (400): " + bindErr.Error()
		}
		fmt.Printf("== %s\n   %s\n   -> %s\n", b.name, b.body, status)
	}
}
